FROM nginx:alpine
WORKDIR /var/www/vpnTelegram
COPY ./.docker/nginx.dev/nginx.conf /etc/nginx/nginx.conf
RUN rm /etc/nginx/conf.d/*.conf
COPY ./.docker/nginx.dev/conf.d/default.conf /etc/nginx/conf.d/default.conf
# apline based = ubuntu => apk istead apt
RUN apk update && apk add openssl
#RUN rm /etc/nginx.dev/conf.d/default.conf && mkdir -p /home/web/www
CMD ["nginx"]
