version: '3'
services:
    db:
        container_name: vpn_db
        image: 'mysql:latest'
        restart: always
        volumes:
            - 'db:/var/lib/mysql'
            - '.docker/mysql/my.cfg:/etc/mysql/my.cnf'
        environment:
            MYSQL_DATABASE: vpn_mysql
            MYSQL_ROOT_PASSWORD: sAA2rnf42
        ports:
            - '3306:3306'
        command: 'mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci'
    app:
        container_name: vpn_app
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        environment:
            PHP_IDE_CONFIG: serverName=vpn
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        depends_on:
            - db
        volumes:
            - '../:/var/www'
        ports:
            - '9003:9003'
    nginx:
        image: 'nginx:latest'
        build:
            context: .
            dockerfile: .docker/nginx.dev/Dockerfile.prod
        ports:
            - '80:80'
            - '443:443'
        links:
            - app
        volumes:
            - './:/var/www/vpnTelegram'
            - '.docker/nginx.dev/conf.d:/etc/nginx/conf.d'
#            - '.docker/certbot/conf:/etc/letsencrypt'
#            - '.docker/certbot/www/:/var/www/certbot'
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
#    certbot:
#        image: certbot/certbot
#        volumes:
#            - '.docker/certbot/conf:/etc/letsencrypt'
#            - '.docker/certbot/www/:/var/www/certbot'
#        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    redis:
        container_name: vpn_redis
        build:
            context: .docker/redis
        restart: unless-stopped
        ports:
            - '6379:6379'
        volumes:
            - 'redis:/data'
    phpmyadmin:
        image: linuxserver/phpmyadmin
        links:
            - db
        ports:
            - '8080:80'
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: sAA2rnf42

volumes:
    db: null
    app: null
    redis: null
    nginx: null
